-- Base de datos actualizada según el documento (tablas: categoria, cliente, promocion, producto, pedido, liniapedido)
-- Dialecto: PostgreSQL

BEGIN;

-- Eliminación en orden para respetar claves foráneas
DROP TABLE IF EXISTS liniapedido;
DROP TABLE IF EXISTS pedido;
DROP TABLE IF EXISTS producto;
DROP TABLE IF EXISTS promocion;
DROP TABLE IF EXISTS cliente;
DROP TABLE IF EXISTS categoria;

CREATE TABLE categoria (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  categoria   varchar,
  descripcion varchar,
  img         varchar
);

CREATE TABLE cliente (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre      varchar,
  password    varchar,
  email       varchar,
  direccion   varchar,
  poblacion   varchar,
  cp          integer,
  img_perfil  varchar
);

CREATE TABLE promocion (
  id        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  descuento varchar,
  valor     numeric
);

CREATE TABLE producto (
  id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  idcategoria  integer NOT NULL,
  id_promocion integer,
  nombre       varchar,
  precio       numeric,
  descripcion  varchar,
  imagen       varchar,
  disponible   boolean,
  CONSTRAINT fk_producto_categoria
    FOREIGN KEY (idcategoria) REFERENCES categoria(id),
  CONSTRAINT fk_producto_promocion
    FOREIGN KEY (id_promocion) REFERENCES promocion(id)
);

CREATE TABLE pedido (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  idusuario   integer NOT NULL,
  fecha       timestamp with time zone NOT NULL DEFAULT now(),
  nelementos  integer NOT NULL,
  importetotal numeric NOT NULL,
  CONSTRAINT fk_pedido_cliente
    FOREIGN KEY (idusuario) REFERENCES cliente(id)
);

CREATE TABLE liniapedido (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  idpedido      integer NOT NULL,
  idproducto    integer NOT NULL,
  subtotal      numeric NOT NULL,
  preciounitario numeric NOT NULL,
  cantidad      integer NOT NULL,
  CONSTRAINT fk_liniapedido_pedido
    FOREIGN KEY (idpedido) REFERENCES pedido(id),
  CONSTRAINT fk_liniapedido_producto
    FOREIGN KEY (idproducto) REFERENCES producto(id)
);

-- Índices recomendados para FKs
CREATE INDEX IF NOT EXISTS idx_producto_idcategoria ON producto(idcategoria);
CREATE INDEX IF NOT EXISTS idx_producto_id_promocion ON producto(id_promocion);
CREATE INDEX IF NOT EXISTS idx_pedido_idusuario ON pedido(idusuario);
CREATE INDEX IF NOT EXISTS idx_liniapedido_idpedido ON liniapedido(idpedido);
CREATE INDEX IF NOT EXISTS idx_liniapedido_idproducto ON liniapedido(idproducto);

COMMIT;
